### ISSUE TITLE
does not build if another project uses sumtype

### ISSUE THREAD

**Issue by FraMecca** [pbackus/expectations#3]
Dub can't build a project that includes expectations and another library that uses an updated version of sumtype (example below). Do you think you can upgrade expectations to use a newer version of sumtype?

dub.json
```
{
	"authors": [
		"user"
	],
	"copyright": "Copyright © 2019, user",
	"dependencies": {
		"ddash": "~>0.11.1",
		"expectations": "~>0.2.0"
	},
	"description": "A minimal D application.",
	"license": "proprietary",
	"name": "name"
}
```

dub build
```
Unresolvable dependencies to package sumtype:
  ddash:common 0.11.1 depends on sumtype ~>0.8.0
  expectations 0.2.0 depends on sumtype ~>0.6.2
```

**Comment by pbackus** [comment]
Whoops. I should've read the docs on dub's version specifiers more carefully.

Fixed and tagged as `v0.3.0`.
