### ISSUE TITLE
Using a child of Exception as the error type causes compilation failure

### ISSUE THREAD

**Issue by unleashy** [pbackus/expectations#4]
Hi! I have this code:

```d
import expectations;

final class A : Exception
{
    import std.exception : basicExceptionCtors;
    mixin basicExceptionCtors;
}

alias EA = Expected!(string, A);

void main()
{}
```

When compiling it under dmd v2.084.0, I get this rather cryptic error at compile time:

```d
sumtype.d(1018,4): Error: static assert:  "handler `__lambda1` of type `inout(A) function(inout(A) err) pure nothrow @nogc @safe` never matches"
sumtype.d(838,14):        instantiated from here: `matchImpl!(inout(SumType!(string, A)))`
expectations.d(206,14):        instantiated from here: `tryMatch!(inout(SumType!(string, A)))`
asd.d(9,12):        instantiated from here: `Expected!(string, A)`
```

The error only seems to happen if the error type is derived from `Exception`. Replacing `mixin basicExceptionCtors;` with the exact same constructors as `Exception` still causes the error.

Is this a bug or am I doing something wrong? Thanks!

**Comment by pbackus** [comment]
Thanks for reporting. This was actually a bug in `sumtype`. If you upgrade to sumtype 0.8.4, it should be fixed.

**Comment by unleashy** [comment]
Yep, it works perfectly now. Thank you!
